### ISSUE TITLE
ArgumentParser_manual_test.vim が正しく動作していないぽい？

### ISSUE THREAD

**Issue by osyo-manga** [lambdalisue/vital-ArgumentParser#1]
doc にも記載されている `ArgumentParser_manual_test.vim` のコードですが `:Hoge! --foo --bar --hoge a --piyo Hi` を行うとパースに失敗するようです。

``` vim
" :Hoge! --foo --bar --hoge a --piyo Hi の実行結果
Invalid value in SWITCH:
ahya argument is SWITCH argument but AHYA is specified
Canceled.
{}
```

**Comment by lambdalisue** [comment]
あー完全に `kind` の指定忘れてますね…ご報告ありがとうございます。

``` vim
call s:parser.add_argument('--ahya', '-a',
        \ 'description of the argument', {
        \ 'default': 'AHYA',
        \ 'kind': s:paerser.kinds.value,
        \})
```

となるべきでした。この辺ドキュメント化されてないですね…

https://github.com/lambdalisue/vital-ArgumentParser/blob/master/doc/vital-argument-parser.txt#L259
https://github.com/lambdalisue/vital-ArgumentParser/blob/master/autoload/vital/__latest__/ArgumentParser.vim#L107

**Comment by osyo-manga** [comment]
なるほど。
ところで話は変わるんですが、ArgumentParser で `--xxx` みたいなオプション以外の引数を取得（パース）することって可能なのでしょうか。
（例えば :Unite コマンドのように `:Unite [{options}] {sources}` の `{source}` 部分を取得する的な。

**Comment by lambdalisue** [comment]
ArgumentParser の恩恵（自動バリデーション・自動補完）を受けない形ならば可能で、返り値の `__unknown__` に指定順で入ります([参考](https://github.com/lambdalisue/vital-ArgumentParser/blob/master/autoload/vital/__latest__/ArgumentParser.vim#L241-L263))。
なので `Unite: [{options}] {sources}` くらい簡単な構文であれば ArgumentParser で処理後に得られる辞書の `__unknown__` を参照し、自分でパース（この場合は `{sources}` に何が指定されたのか？）を行えばOKです。オプション部分は ArgumentParser の恩恵を受けられるので利用価値もあります。

ちなみに若干複雑になりますが `pre_completion` や `pre_validation` などのフックも存在しているため、たとえ `__unknown__` に入っていても上記フックに渡された `a:args.__unknown__` をパースして挙動を変化させるコードを書けば「ある特定のソースが指定された場合にだけ有効に成るオプション」みたいなこともできます（似たようなことを [vim-gista](https://github.com/lambdalisue/vim-gista/blob/master/autoload/gista/arguments.vim#L182-L235) でやっています、`__unknown__`は使ってないですが）。

P.S.

``` vim
let s:parser = s:P.new({'validate_unknown': 0})
```

is required without using `pre_validation`.

https://github.com/lambdalisue/vital-ArgumentParser/blob/master/doc/vital-argument-parser.txt#L228
https://github.com/lambdalisue/vital-ArgumentParser/blob/master/autoload/vital/__latest__/ArgumentParser.vim#L542

**Comment by osyo-manga** [comment]
なるほど。ありがとうございます。

> 「ある特定のソースが指定された場合にだけ有効に成るオプション」

サブコマンドみたいなのを作りたい場合にこういうのは便利そうですね。

**Comment by lambdalisue** [comment]
あ、ちょっと今忙しくて最初に指摘していただいた部分の修正ができていないので再オープンします。修正後こちらで閉じますね。

**Comment by osyo-manga** [comment]
了解っす。

**Comment by lambdalisue** [comment]
Closed in https://github.com/lambdalisue/vital-ArgumentParser/commit/c41ab11d057b105fc58c93a2d332ae4e12cc0b9a
