### ISSUE TITLE
add_argument() 時に 'default' を指定した場合にコマンドの補完の候補に上がらない

### ISSUE THREAD

**Issue by osyo-manga** [lambdalisue/vital-ArgumentParser#2]
次のように `'default'` を指定して引数の設定を行った場合にコマンドの補完に `--ahya` が列挙されないのですが、これを補完に含めるにはどうすればよいのでしょうか。

``` vim
let s:V = vital#of('vital')
let s:P = s:V.import('ArgumentParser')
let s:parser = s:P.new({'validate_unknown': 0})

" こっちは補完の候補に出る
call s:parser.add_argument('--foo', '-f',
    \ 'description of the argument', {
    \ 'kind': s:parser.kinds.value,
    \})

" default が設定されている場合に補完の候補がでない
call s:parser.add_argument('--ahya', '-a',
    \ 'description of the argument', {
    \ 'default': 'AHYA',
    \ 'kind': s:parser.kinds.any,
    \})

" sample function
function! Command(...)
  echo call(s:parser.parse, a:000, s:parser)
endfunction

function! Complete(...)
  return call(s:parser.complete, a:000, s:parser)
endfunction

" sample command
command! -nargs=? -range=% -bang
    \ -complete=customlist,Complete Hoge
    \ :call Command(<q-bang>, [<line1>, <line2>], <f-args>)
```

![](http://i.gyazo.com/bd4537269c165c00e5b174640b8a0d31.png)

この時に `--ahya` や `-a` も候補に上がって欲しい。

**Comment by lambdalisue** [comment]
なるほど。方法が3つあります。

### v2 を利用する

現在 vim-gita で
1. positional argument (`:Gita browse`)
2. `=` assignment (`:Gita --foo=bar`)
3. Terminal argument (`:Gita browse yank` で `browse` 部分が terminal argument parser であれば `yank` は `__unknown__` に入るため再度別の ArgumentParser で処理可能)

などの機能を使いたいため v2 の開発を v2 ブランチで行っております。そこでは上記の問題も解決していますが
1. 上記機能を扱うため + 構造を簡単にするためにAPIの変更が加わっている (`add_argument` も変わってます）
2. 仕様が固まっていない（vim-gitaで使いやすく変える可能性がある + 仕様がほぼ確定した後に最終版への使用調整が入る可能性が大）
3. 上記のためドキュメントが存在していない

などの問題点もあります。かなりα版です。最終的には v1 -> v2 の移行が簡単にできるような構造にする可能性もあるので、今から使いはじめるのは辛いかもしれません。

### Hook を利用してデフォルトを指定する

Hook を利用することでデフォルトを指定すれば complete 用の candidate には含まれないため現状でも問題ないはずです。
https://github.com/lambdalisue/vital-ArgumentParser/blob/master/autoload/vital/__latest__/ArgumentParser.vim#L505
で加える 

or 

https://github.com/lambdalisue/vital-ArgumentParser/blob/master/autoload/vital/__latest__/ArgumentParser.vim#L654
で消す

### 修正を待つ

v2 開発時に上記問題には気づいていたため原因はわかっております（https://github.com/lambdalisue/vital-ArgumentParser/blob/master/autoload/vital/__latest__/ArgumentParser.vim#L238 にてデフォルトを最初に指定しちゃうのが問題。`_parse_cmdline` は complete 用 candidates を作るためにも使っている）
ただ、これを `_parse_cmdline` 外に移動させた時に通らなくなるテストなどがあると考えられるため重い腰が上がっていなかった状況です、が、使ってる人いないだろうなーという感想から優先度がとても下がっていただけなので osyo-manga さんにご利用いただいているというのであれば、優先度を上げて処理いたします。

**Comment by osyo-manga** [comment]
丁寧にありがとうございます。
issues にコメントしたあとにいろいろと試してみた結果、結局 `'default'` を使わないような書き方になったので現状、特に困っているわけではないです。
次期バージョンで対応されているのであれば（わたしは）それで問題ないと思います。

**Comment by lambdalisue** [comment]
了解しました。ご利用いただいているということで、移行がなるべく簡単に出来るように次期バージョン作ろうと心に決めましたwとりあえずissueは次期が出るまでは開けたままにしておきます

**Comment by osyo-manga** [comment]
> 移行がなるべく簡単に出来るように次期バージョン作ろうと心に決めましたw

今はまだあまり利用しきれていないので、変更点や移行手段なんかをどこか（ブログ等）でまとめてもらえるのであれば互換性はそこまで気にしなくても大丈夫です。
最悪、既存のものはそのままで、新規プラグインから対応するということもできますしねぇ。

**Comment by osyo-manga** [comment]
ちなみに使っているコードはこんな感じです。
https://github.com/osyo-manga/vim-hopping/blob/master/autoload/hopping.vim#L344

**Comment by lambdalisue** [comment]
そのコードであればv2にすぐに移行できますねー良かった。

**Comment by osyo-manga** [comment]
便利そう
vital-ArgumentParser 自体はコマンドラインが必要なプラグインであれば使っていこうとは考えています（ただし、コマンドラインが必要なプラグインを作る予定はあまりなかったりします（オレオレ vital モジュールつくりたくてつらい

**Comment by lambdalisue** [comment]
ありがとうございます。早めに v2 のドキュメント整備します（笑。
vital モジュール作るの楽しい。

**Comment by lambdalisue** [comment]
v2 出たので閉じます

**Comment by osyo-manga** [comment]
おっ、了解です。

**Comment by lambdalisue** [comment]
osyoさんは使っていないようですが `kind` -> `type` という命名変更がありますのでご注意ください
